[phases.setup]
nixPkgs = ["gcc", "python39"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt --no-cache-dir"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python start_backend.py --host 0.0.0.0 --port $PORT" 