[phases.setup]
nixPkgs = ["python39", "gcc", "g++"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python main.py"